Repository growingnet/gromo, pull requests merged in 2024-12, with the labels that each got.

#7 feat(GrowingModule): Improve error message in extended_forward and improve __str__
  .gitignore
  src/gromo/growing_module.py
  tests/test_growing_module.py
Labels: enhancement

#15 Correct doc readme
  .github/workflows/doc.yml
  docs/source/README.rst
Labels: documentation, enhancement

#14 Code merging
  .gitignore
  docs/source/whats_new.rst
  pyproject.toml
  src/gromo/graph_network/GrowableDAG.py
  src/gromo/graph_network/dag_growing_network.py
  src/gromo/growing_module.py
  src/gromo/main_graph_network.py
  src/gromo/script/main_graph_network.py
  src/gromo/utils/logger.py
  src/gromo/utils/profiling.py
  src/gromo/utils/utils.py
  tests/test_GrowableDAG.py
  tests/test_dag_growing_network.py
  tests/test_growing_module.py
  tests/test_logger.py
Labels: documentation, enhancement

#10 docs: Strat the technical notes
  docs/source/conf.py
  docs/source/images/gromo_links.png
  docs/source/index.rst
  docs/source/tech_notes.rst
  src/gromo/growing_module.py
Labels: documentation, help wanted

#25 Fix tests badge on README
  README.md
Labels: enhancement

#24 fix: Supsicious Assertion #23 (fix #23)
  src/gromo/growing_module.py
Labels: bug

#16 Latest features update
  .gitignore
  docs/source/whats_new.rst
  pyproject.toml
  src/gromo/graph_network/GrowableDAG.py
  src/gromo/graph_network/dag_growing_network.py
  src/gromo/script/main_graph_network.py
  src/gromo/utils/gpu_tracking.py
  src/gromo/utils/logger.py
  src/gromo/utils/utils.py
  tests/test_GrowableDAG.py
  tests/test_dag_growing_network.py
  tests/test_growing_module.py
  tests/test_logger.py
  tests/test_utils.py
Labels: enhancement

#17 Conv2dGrowingModule implementation of natural gradient
  src/gromo/conv2d_growing_module.py
  tests/test_conv2d_growing_module.py
Labels: enhancement

#18 Docs: Tech notes on statistics compuation
  docs/source/images/gromo_statistics.png
  docs/source/tech_notes.rst
Labels: documentation

#22 feat: Add tests for mask tensor t
  misc/test_theory_v2.ipynb
  tests/test_tools.py
Labels: test
