Repository growingnet/gromo, pull requests merged in 2025-04, with the labels that each got.

#84 Petition to rename AdditionGrowingModule to MergeGrowingModule!
  docs/source/whats_new.rst
  examples/plot_growing_network.py
  src/gromo/containers/growing_block.py
  src/gromo/containers/growing_container.py
  src/gromo/containers/growing_dag.py
  src/gromo/containers/growing_graph_network.py
  src/gromo/modules/conv2d_growing_module.py
  src/gromo/modules/growing_module.py
  src/gromo/modules/linear_growing_module.py
  tests/test_conv2d_growing_module.py
  tests/test_growing_dag.py
  tests/test_linear_growing_module.py
Labels: enhancement, code-breaking

#86 fix: Use the correct name for the tensor statistics
  src/gromo/modules/growing_module.py
Labels: incorret behavior

#89 enh: Add an installation guide
  README.md
Labels: documentation
