Repository growingnet/gromo, pull requests merged in 2025-03, with the labels that each got.

#74 fix: Adding new neurons without natural gradient step.
  docs/source/conf.py
  docs/source/tech_notes.rst
  docs/source/whats_new.rst
  examples/plot_linear_module.py
  src/gromo/modules/growing_module.py
  src/gromo/modules/linear_growing_module.py
  tests/test_linear_growing_module.py
Labels: bug

#73 Ref: structure DAG expansion info in class
  docs/source/whats_new.rst
  src/gromo/containers/growing_dag.py
  src/gromo/containers/growing_graph_network.py
  src/gromo/utils/utils.py
  tests/test_growing_dag.py
  tests/test_growing_graph_network.py
Labels: enhancement

#81 !fix: Fix #80 and add a test that detect the fixed bug
  src/gromo/modules/conv2d_growing_module.py
  tests/test_conv2d_growing_module.py
Labels: bug, code-breaking

#82 enh: Change the logo
  README.md
  docs/source/README.rst
  docs/source/conf.py
  docs/source/images/logo_bg_black.png
  docs/source/images/logo_bg_white_small.png
Labels: documentation
