Repository growingnet/gromo, pull requests merged in 2025-01, with the labels that each got.

#40 feat: Test class for code using torch
  .gitignore
  tests/test_linear_growing_module.py
  tests/torch_unittest.py
Labels: enhancement, test

#41 !fix: sub_select_optimal_added_parameters
  docs/source/whats_new.rst
  src/gromo/growing_module.py
  src/gromo/linear_growing_module.py
  tests/test_linear_growing_module.py
Labels: bug, code-breaking

#33 feat: Create support for tensor S growth
  docs/source/images/gromo_statistics.png
  docs/source/tech_notes.rst
  docs/source/whats_new.rst
  src/gromo/growing_module.py
  src/gromo/linear_growing_module.py
  tests/test_linear_growing_module.py
Labels: invalid

#46 Reduce unit tests time
  .github/workflows/whats-new.yml
  docs/source/whats_new.rst
  tests/test_tools.py
  tests/unittest_tools.py
Labels: enhancement

#48 !fix: Correct bugs in `extended_forward` and `apply_change`
  docs/source/whats_new.rst
  src/gromo/graph_network/dag_growing_network.py
  src/gromo/growing_module.py
  tests/test_growing_module.py
  tests/test_linear_growing_module.py
Labels: bug, code-breaking

#34 feat: Implement extension of Conv2d layers
  docs/source/whats_new.rst
  src/gromo/conv2d_growing_module.py
  tests/test_conv2d_growing_module.py
Labels: enhancement

#57 fix: Fix the value of some default arguments
  misc/mlp_run.py
Labels: bug, documentation

#58 fix: data augmentation
  docs/source/whats_new.rst
  src/gromo/utils/datasets.py
Labels: bug
