Repository growingnet/gromo, pull requests merged in 2025-09, with the labels that each got.

#115 !fix(GrowingModule._auxiliary_compute_alpha_omega): Fix a sign error
  src/gromo/modules/growing_module.py
Labels: bug

#138 Fix memory leak in tensor updates
  docs/source/whats_new.rst
  src/gromo/modules/growing_module.py
  src/gromo/utils/tensor_statistic.py
Labels: bug, enhancement

#106 enh: Completed the `GrowingBlock` class
  docs/source/whats_new.rst
  src/gromo/containers/growing_block.py
  tests/test_conv2d_growing_block.py
  tests/test_growing_block.py
Labels: enhancement
